name: flutter_guards
description: Contains LoadingGuard, AuthGuard, FutureGuard, StreamGuard 
version: 0.0.1
homepage: https://github.com/cedvdb/flutter_guards.git
repository: https://github.com/cedvdb/flutter_guards.git


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
